### ISSUE TITLE
Query on emacs packages

### ISSUE THREAD

**Issue by Nequo** [mattray/home-directory#1]
Hi Matt! Came here from the youtube video on your talk about Interactive Remote Debugging and Development with TRAMP Mode - great stuff. I have been using spacemacs/doom coming from vim but am interested in rolling out an emacs config myself. I like the way you arrange your files but I had a question on installing packages. Do you just do it manually or is there something I have missed? Thanks!

**Comment by mattray** [comment]
For MacOS I tend to install things manually, despite working for an
automation company. My Linux boxes are all automated, but my laptop is not
(yet).
